name: Build fastai2 images
on: 
  schedule:
    - cron: '1 6 * * *'
  workflow_dispatch: #allows you to trigger manually

jobs:
  build-prod:
    env:
      IMAGE_NAME: "fastdotai/fastai2"
    runs-on: ubuntu-latest
    steps:

    - name: Copy Repository Contents
      uses: actions/checkout@main
      with:
        repository: 'fastai/fastai2'
   
    - name: Copy This Repository Contents
      uses: actions/checkout@main
      with:
        path: 'docker/'  
  
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        architecture: 'x64'

    - name: get version from settings.ini
      id: get_version
      run: |
        from configparser import ConfigParser
        config = ConfigParser()
        config.read('settings.ini')
        cfg = config['DEFAULT']
        print(f"::set-output name=version::{cfg['version']}")
      shell: python

    - name: clean files
      run: |
        sudo apt-get update -y
        sudo apt-get install dos2unix
        find . -type f -print0 | xargs -0 dos2unix --

    - name: build and tag container
      run: |
        docker pull ${IMAGE_NAME}:latest || true
        docker build -t ${IMAGE_NAME}:latest -f docker/fastai2-build/Dockerfile .
        docker tag ${IMAGE_NAME}:latest ${IMAGE_NAME}:${VERSION}
      env:
        VERSION: ${{ steps.get_version.outputs.version }}

    - name: push images to DockerHub
      run: |
        echo ${PASSWORD} | docker login -u $USERNAME --password-stdin
        docker push ${IMAGE_NAME}:latest
        docker push ${IMAGE_NAME}:${VERSION}
      env:
        USERNAME: ${{ secrets.DOCKER_USERNAME }}
        PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  build-dev:
    env:
      IMAGE_NAME: "fastdotai/fastai2-dev"
    runs-on: ubuntu-latest
    steps:

    - name: Copy Repository Contents
      uses: actions/checkout@main
      with:
        repository: 'fastai/fastai2'
    
    - name: Copy This Repository Contents
      uses: actions/checkout@main
      with:
        path: 'docker/' 

    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        architecture: 'x64'

    - name: get version from settings.ini
      id: get_version
      run: |
        from configparser import ConfigParser
        config = ConfigParser()
        config.read('settings.ini')
        cfg = config['DEFAULT']
        print(f"::set-output name=version::{cfg['version']}")
      shell: python

    - name: clean files
      run: |
        sudo apt-get update -y
        sudo apt-get install dos2unix
        find . -type f -print0 | xargs -0 dos2unix --

    - name: build and tag container
      run: |
        docker pull ${IMAGE_NAME}:latest || true
        docker build -t ${IMAGE_NAME}:latest -f docker/fastai2-build/Dockerfile .
        docker tag ${IMAGE_NAME}:latest ${IMAGE_NAME}:${VERSION}
      env:
        VERSION: ${{ steps.get_version.outputs.version }}

    - name: push images to DockerHub
      run: |
        echo ${PASSWORD} | docker login -u $USERNAME --password-stdin
        docker push ${IMAGE_NAME}:latest
        docker push ${IMAGE_NAME}:${VERSION}
      env:
        USERNAME: ${{ secrets.DOCKER_USERNAME }}
        PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
