  
name: Build fastai2 ci images
on: 
  schedule:
    - cron: '1 9 * * *'
  workflow_dispatch: #allows you to trigger manually
  push:
    branches:
      - master
    paths:
      - 'fastai2-ci/**'

jobs:
  build:
    env:
      IMAGE_NAME: "fastdotai/fastai2-ci"
    runs-on: ubuntu-latest
    steps:
   
    - name: Copy This Repository Contents
      uses: actions/checkout@main

    - name: build and tag container
      run: |
        docker build --squash \
          -t ${IMAGE_NAME}:latest \
          -t ${IMAGE_NAME}:$(date +%F) \
          -f fastai2-ci/Dockerfile fastai2-ci

    - name: push images
      run: |
        echo ${PASSWORD} | docker login -u $USERNAME --password-stdin
        docker push ${IMAGE_NAME}
      env:
        USERNAME: ${{ secrets.DOCKER_USERNAME }}
        PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
